export class Transportadora {
  id: number = null;
  email: string = null;
  nome: string = null;
  empresa: string = null;
  cnpj: string = null;
  telefone: string = null;
  celular: string = null;
  whatsapp: string = null;
  cep: string = null;
  ufId: number = null;
  cidade: string = null;
  bairro: string = null;
  logradouro: string = null;
  numero: string = null;
  termo: boolean = null;
  logo: any = null;
  modal: any = null;
  uf: any = null;
}
